"""Initial

Revision ID: 7c07850af9e8
Revises: d2e532721e35
Create Date: 2024-12-26 14:20:07.597546

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c07850af9e8"
down_revision: Union[str, None] = "d2e532721e35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resume_template", sa.Column("parent_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resume_template", "parent_id")
    # ### end Alembic commands ###
